### ISSUE TITLE
Confidence intervals and data type BoxCoxTrans

### ISSUE THREAD

**Issue by lindemann09** [tk3369/BoxCoxTrans.jl#13]
Hi Tom,

it would be nice to extend the package a bit:
- A method to calculate confidence intervals for lambda is missing. This method should overload `StatsAPI.confint( )`.
- For that, `BoxCoxTrans.lambda` should return a struct `BoxCoxTrans(value, details)` and not a NamedTuple. 

Have you already plans for further developments of the package and to merge it with your [YeoJohnsonTrans.jl](https://github.com/tk3369/YeoJohnsonTrans.jl))?

Oliver

See https://github.com/lindemann09/BoxCoxTrans.jl

**Comment by tk3369** [comment]
Hi, unfortunately I have been very busy and not able to spend much time with open source these days. Pull requests are welcome though.

**Comment by tk3369** [comment]
@lindemann09  Just saw your fork. Looks awesome! Let me know if you want to submit a PR. I just happened to update the dependencies so you would have to rebase.

RE: merge with YeoJohnsonTrans package, the "grand" idea was to also add functionalities to find the best normalization result like R's [bestNormalize package](https://cran.r-project.org/web/packages/bestNormalize/vignettes/bestNormalize.html). You can see some prelim work here: https://github.com/khkwong/Normalize.jl

**Comment by tk3369** [comment]
BTW, just found an interesting package that is more up to date. Perhaps it would be a good opportunity to consolidate  https://palday.github.io/BoxCox.jl/stable/

cc: @palday
